spring.application.name=Order-Service

server.port=8088

user.service.url=http://localhost:8087

payment.service.url=http://localhost:8089

spring.main.allow-bean-definition-overriding=true

resilience4j.circuitbreaker.instances.paymentCB.sliding-window-size=5

resilience4j.circuitbreaker.instances.paymentCB.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.paymentCB.wait-duration-in-open-state=10s